# Generated by Django 5.2.7 on 2025-10-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFaculty',
            fields=[
                ('faculty_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Archived Faculty',
                'db_table': 'ArchivedFaculty',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('faculty_status', models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], default='Continuing', max_length=20)),
                ('password_changed', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
    ]
