# Generated by Django 5.2 on 2025-08-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty',
        ),
    ]
