# Generated by Django 5.2.7 on 2025-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profiles/'),
        ),
    ]
