# Generated by Django 5.2.7 on 2025-10-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedfaculty',
            options={},
        ),
        migrations.RemoveField(
            model_name='archivedfaculty',
            name='program',
        ),
        migrations.RemoveField(
            model_name='archivedfaculty',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='archivedfaculty',
            name='year_section',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='program',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='year_section',
        ),
        migrations.AddField(
            model_name='archivedfaculty',
            name='assignments_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='archivedfaculty',
            name='faculty_status',
            field=models.CharField(default='Archived', max_length=20),
        ),
        migrations.AlterModelTable(
            name='archivedfaculty',
            table='Archived_Faculty',
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology')], max_length=50)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Faculty.faculty')),
            ],
            options={
                'db_table': 'Faculty_Assignment',
                'unique_together': {('faculty', 'program', 'year_section', 'semester')},
            },
        ),
    ]
