# Generated by Django 5.2 on 2025-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_alter_faculty_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
