# Generated by Django 5.2 on 2025-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_remove_faculty_id_alter_faculty_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Deactivated', 'Deactivated'), ('Completed', 'Completed')], default='Continuing', max_length=20),
        ),
    ]
