# Generated by Django 5.2 on 2025-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_faculty_faculty_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFaculty',
            fields=[
                ('faculty_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('faculty_status', models.CharField(default='Archived', max_length=20)),
            ],
            options={
                'db_table': 'ArchivedFaculty',
            },
        ),
    ]
