# Generated by Django 5.2 on 2025-08-13 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_archivedfaculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedfaculty',
            name='faculty_status',
        ),
        migrations.AddField(
            model_name='archivedfaculty',
            name='archived_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
