# Generated by Django 5.2 on 2025-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_remove_archivedfaculty_faculty_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedfaculty',
            options={'verbose_name_plural': 'Archived Faculty'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], default='Continuing', max_length=20),
        ),
    ]
