# Generated by Django 5.2 on 2025-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0007_alter_archivedfaculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
