# Generated by Django 5.2 on 2025-08-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_firstName', models.CharField(max_length=100)),
                ('student_lastName', models.CharField(max_length=100)),
                ('student_middleInitial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
