# Generated by Django 5.2.7 on 2025-10-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStudent',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Pending_Students',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(help_text="Unique identifier for the task, e.g., 'novice_task_1'", max_length=100, primary_key=True, serialize=False)),
                ('firestore_key', models.CharField(help_text='The exact field name used in Firestore', max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('Novice', 'Novice'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tasks',
                'ordering': ['tier', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('year_section', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to='Faculty.faculty')),
            ],
            options={
                'db_table': 'Archived_Students',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('student_status', models.CharField(choices=[('Registered', 'Registered'), ('Completed', 'Completed'), ('Drop-out', 'Drop-out')], default='Registered', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_old', to='Faculty.faculty')),
                ('faculty_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Faculty.facultyassignment')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Stores extra data from Firestore like score or timestamp.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='Student.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Student.task')),
            ],
            options={
                'db_table': 'StudentTaskProgress',
                'unique_together': {('student', 'task')},
            },
        ),
    ]
