# Generated by Django 5.2 on 2025-08-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_archivedfaculty'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='program',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_firstName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_middleInitial',
            new_name='middle_initial',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_lastName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_section',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Faculty.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Completed', 'Completed'), ('Dropout', 'Drop-out')], default='Registered', max_length=20),
        ),
    ]
