# Generated by Django 5.2.7 on 2025-10-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
    ]
