# Generated by Django 5.2.7 on 2025-10-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Student', '0002_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedstudent',
            name='faculty_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to='Faculty.facultyassignment'),
        ),
    ]
