# Generated by Django 5.2 on 2025-08-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_archivedfaculty'),
        ('Student', '0002_rename_program_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('student_status', models.CharField(choices=[('Completed', 'Completed'), ('Dropout', 'Drop-out')], max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to='Faculty.faculty')),
            ],
            options={
                'verbose_name_plural': 'Archived Students',
                'db_table': 'ArchivedStudents',
            },
        ),
    ]
