# Generated by Django 5.2.7 on 2025-10-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_auto_20251004_0627'),
        ('Student', '0002_auto_20251004_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedstudent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pendingstudent',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_section',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Faculty.facultyassignment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_old', to='Faculty.faculty'),
        ),
        migrations.AlterModelTable(
            name='archivedstudent',
            table='Archived_Students',
        ),
        migrations.AlterModelTable(
            name='pendingstudent',
            table='Pending_Students',
        ),
    ]
