# Generated by Django 5.2 on 2025-08-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_archivedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='student_status',
        ),
    ]
