# Generated by Django 5.2.7 on 2025-11-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_archivedstudent_faculty_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
