# Generated by Django 5.2.7 on 2025-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedstudent',
            name='firebase_uid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
