# Generated by Django 5.2 on 2025-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_remove_archivedstudent_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStudent',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('year_section', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pending Students',
                'db_table': 'PendingStudents',
            },
        ),
    ]
