# Generated by Django 5.2 on 2025-08-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_pendingstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(help_text="Unique identifier for the task, e.g., 'novice_task_1'", max_length=100, primary_key=True, serialize=False)),
                ('firestore_key', models.CharField(help_text='The exact field name used in Firestore', max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('Novice', 'Novice'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tasks',
                'ordering': ['tier', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Stores extra data from Firestore like score or timestamp.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='Student.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Student.task')),
            ],
            options={
                'db_table': 'StudentTaskProgress',
                'unique_together': {('student', 'task')},
            },
        ),
    ]
