# Generated by Django 5.2 on 2025-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_task_studenttaskprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='id',
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='year_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='year_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='archivedstudent',
            name='student_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
