# Generated by Django 5.2 on 2025-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_remove_archivedstudent_id_archivedstudent_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Completed', 'Completed'), ('Drop-out', 'Drop-out')], default='Registered', max_length=20),
        ),
    ]
